import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/src/ui/theme';

export function makeSettingsStyles(theme: AppTheme) {
  return StyleSheet.create({
    scroll: { flex: 1, backgroundColor: theme.color.canvas },
    container: { padding: theme.space.lg, gap: theme.space.md, paddingBottom: 48 },
    window: { ...theme.type.caption, color: theme.color.primary, fontWeight: '600' },
    row: { flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
    switchRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
      gap: 8,
    },
    switchLabel: { flex: 1, color: theme.color.ink, fontSize: 14 },
    stepper: { gap: 4, marginTop: 4 },
    stepperLabel: { fontSize: 13, color: theme.color.inkSecondary },
    stepperVal: {
      minWidth: 28,
      textAlign: 'center',
      fontWeight: '700',
      fontSize: 16,
      color: theme.color.ink,
    },
    sampleLabel: { fontWeight: '600', fontSize: 13, color: theme.color.ink, marginTop: 4 },
    sample: {
      fontSize: 11,
      fontFamily: 'SpaceMono',
      backgroundColor: theme.color.surfaceMuted,
      padding: 10,
      borderRadius: theme.radius.sm,
      color: theme.color.inkSecondary,
    },
    contact: { fontSize: 14, fontWeight: '600', color: theme.color.ink },
    input: {
      borderWidth: 1,
      borderColor: theme.color.border,
      borderRadius: theme.radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: theme.color.ink,
      backgroundColor: theme.color.surfaceMuted,
      fontSize: 14,
    },
    inputMulti: {
      borderWidth: 1,
      borderColor: theme.color.border,
      borderRadius: theme.radius.sm,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: theme.color.ink,
      backgroundColor: theme.color.surfaceMuted,
      fontSize: 13,
      minHeight: 72,
      textAlignVertical: 'top' as const,
    },
    menuCard: { paddingVertical: 4, gap: 0 },
    menuRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      paddingHorizontal: 4,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.color.border,
    },
    menuRowLast: { borderBottomWidth: 0 },
    menuTextWrap: { flex: 1, gap: 2 },
    menuTitle: { fontSize: 16, fontWeight: '600', color: theme.color.ink },
    menuMeta: { fontSize: 12, color: theme.color.inkMuted, lineHeight: 16 },
    menuChevron: { fontSize: 22, color: theme.color.inkFaint, fontWeight: '300' },
    dienstList: {
      marginTop: 4,
      borderRadius: theme.radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.color.border,
      overflow: 'hidden',
      backgroundColor: theme.color.surfaceMuted,
    },
    dienstRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.color.border,
    },
    dienstRowLast: { borderBottomWidth: 0 },
    dienstDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    dienstTextWrap: { flex: 1, gap: 2 },
    dienstTitle: { fontSize: 15, fontWeight: '600', color: theme.color.ink },
    dienstMeta: { fontSize: 12, color: theme.color.inkMuted },
    dienstTimes: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.color.primary,
      maxWidth: '42%',
      textAlign: 'right',
    },
    dienstEditor: {
      paddingHorizontal: 12,
      paddingBottom: 14,
      gap: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.color.border,
      backgroundColor: theme.color.canvas,
    },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
    timeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.color.surfaceMuted,
      borderWidth: 1,
      borderColor: theme.color.border,
    },
    timeChipText: { fontSize: 14, fontWeight: '600', color: theme.color.ink },
    timeChipX: { fontSize: 16, color: theme.color.inkMuted, fontWeight: '600' },
  });
}

export type SettingsStyles = ReturnType<typeof makeSettingsStyles>;
