/* AUTO-GENERATED by scripts/packs/generate-registry.cjs — do not edit */
import type { PackMapping } from '../convert/types';
import type { PayrollProfile } from '../payroll/types';
import type { PackPdfConfig } from '../convert/parsers/engines';
import type { PackOcrConfig, PackOcrScopeConfig, PackConfigJson } from './types';

import config_default_generic from './builtin/default-generic/config.json';
import ocr_default_generic from './builtin/default-generic/parsers/ocr.json';
import pdf_default_generic from './builtin/default-generic/parsers/pdf.json';
import map_default_generic_mappings_generic_json from './builtin/default-generic/mappings/generic.json';
import config_st_elisabeth_leipzig from './builtin/st-elisabeth-leipzig/config.json';
import ocr_st_elisabeth_leipzig from './builtin/st-elisabeth-leipzig/parsers/ocr.json';
import pdf_st_elisabeth_leipzig from './builtin/st-elisabeth-leipzig/parsers/pdf.json';
import map_st_elisabeth_leipzig_mappings_pflege_op_ata_json from './builtin/st-elisabeth-leipzig/mappings/pflege/op-ata.json';
import pay_st_elisabeth_leipzig_mappings_pflege_krankenhaus_payroll_json from './builtin/st-elisabeth-leipzig/mappings/pflege/krankenhaus.payroll.json';
import map_st_elisabeth_leipzig_mappings_pflege_op_ota_json from './builtin/st-elisabeth-leipzig/mappings/pflege/op-ota.json';
import map_st_elisabeth_leipzig_mappings_pflege_station_standard_json from './builtin/st-elisabeth-leipzig/mappings/pflege/station-standard.json';
import map_st_elisabeth_leipzig_mappings_pflege_station_16_json from './builtin/st-elisabeth-leipzig/mappings/pflege/station-16.json';
import map_st_elisabeth_leipzig_mappings_service_op_json from './builtin/st-elisabeth-leipzig/mappings/service/op.json';
import pay_st_elisabeth_leipzig_mappings_service_krankenhaus_payroll_json from './builtin/st-elisabeth-leipzig/mappings/service/krankenhaus.payroll.json';
import map_st_elisabeth_leipzig_mappings_service_station_standard_json from './builtin/st-elisabeth-leipzig/mappings/service/station-standard.json';
import map_st_elisabeth_leipzig_mappings_service_station_16_json from './builtin/st-elisabeth-leipzig/mappings/service/station-16.json';
import map_st_elisabeth_leipzig_mappings_arzt_op_anaesthesie_json from './builtin/st-elisabeth-leipzig/mappings/arzt/op-anaesthesie.json';
import pay_st_elisabeth_leipzig_mappings_arzt_krankenhaus_payroll_json from './builtin/st-elisabeth-leipzig/mappings/arzt/krankenhaus.payroll.json';
import ocrp_st_elisabeth_leipzig_mappings_arzt_op_anaesthesie_ocr_json from './builtin/st-elisabeth-leipzig/mappings/arzt/op-anaesthesie.ocr.json';

export type PackRegistryEntry = {
  id: string;
  config: PackConfigJson;
  ocr: PackOcrConfig;
  pdf: PackPdfConfig;
  mappingsByPath: Record<string, PackMapping>;
  payrollByPath: Record<string, PayrollProfile>;
  ocrByPath: Record<string, PackOcrScopeConfig>;
};

export const PACK_REGISTRY: PackRegistryEntry[] = [
  {
    id: "default-generic",
    config: config_default_generic as PackConfigJson,
    ocr: ocr_default_generic as PackOcrConfig,
    pdf: pdf_default_generic as PackPdfConfig,
    mappingsByPath: {
    "mappings/generic.json": map_default_generic_mappings_generic_json as PackMapping,
    },
    payrollByPath: {

    },
    ocrByPath: {

    },
  },
  {
    id: "st-elisabeth-leipzig",
    config: config_st_elisabeth_leipzig as PackConfigJson,
    ocr: ocr_st_elisabeth_leipzig as PackOcrConfig,
    pdf: pdf_st_elisabeth_leipzig as PackPdfConfig,
    mappingsByPath: {
    "mappings/pflege/op-ata.json": map_st_elisabeth_leipzig_mappings_pflege_op_ata_json as PackMapping,
    "mappings/pflege/op-ota.json": map_st_elisabeth_leipzig_mappings_pflege_op_ota_json as PackMapping,
    "mappings/pflege/station-standard.json": map_st_elisabeth_leipzig_mappings_pflege_station_standard_json as PackMapping,
    "mappings/pflege/station-16.json": map_st_elisabeth_leipzig_mappings_pflege_station_16_json as PackMapping,
    "mappings/service/op.json": map_st_elisabeth_leipzig_mappings_service_op_json as PackMapping,
    "mappings/service/station-standard.json": map_st_elisabeth_leipzig_mappings_service_station_standard_json as PackMapping,
    "mappings/service/station-16.json": map_st_elisabeth_leipzig_mappings_service_station_16_json as PackMapping,
    "mappings/arzt/op-anaesthesie.json": map_st_elisabeth_leipzig_mappings_arzt_op_anaesthesie_json as PackMapping,
    },
    payrollByPath: {
    "mappings/pflege/krankenhaus.payroll.json": pay_st_elisabeth_leipzig_mappings_pflege_krankenhaus_payroll_json as PayrollProfile,
    "mappings/service/krankenhaus.payroll.json": pay_st_elisabeth_leipzig_mappings_service_krankenhaus_payroll_json as PayrollProfile,
    "mappings/arzt/krankenhaus.payroll.json": pay_st_elisabeth_leipzig_mappings_arzt_krankenhaus_payroll_json as PayrollProfile,
    },
    ocrByPath: {
    "mappings/arzt/op-anaesthesie.ocr.json": ocrp_st_elisabeth_leipzig_mappings_arzt_op_anaesthesie_ocr_json as PackOcrScopeConfig,
    },
  }
];

export const SMOKE_DEFAULT_PACK_ID: string | null = "st-elisabeth-leipzig";
